### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by NB2002** [BarthPaleologue/volumetric-atmospheric-scattering#5]
Hey, amazing post process, great work. Exactly what I was looking for. The problem is when I combine this post process with my LOD planet, I get these visual glitches everytime the terrain updates. (video) Any idea what the problem/fix could be? (I'm speculating that the problem might have something to do with the depth buffer).

https://user-images.githubusercontent.com/18073837/185492045-60b472ab-fbf0-48f9-828d-3382f46b649e.mp4

**Comment by BarthPaleologue** [comment]
Hi there !

Thank you for using my shader :) I encountered the same problem with my own LOD planets actually so i know exactly the issue.

Your intuition is correct as it is related to the depth buffer. When you remove the meshes to change the LOD there is a few frames where the depth buffer thinks there is nothing where your planet is. It probably is a bug of BabylonJS if you are using it too.

What I did is overriding the depthbuffer to manage the visible meshes manually : 

First override its behavior by doing : 
```ts
depthRenderer.getDepthMap().renderList = [];
```

Then for each of your meshes you add them yourself : 
```ts
depthRenderer.getDepthMap().renderList?.push(task.chunk.mesh);
```

The issue with this method is that you need to add all your meshes manually and you might forget one or two, leading to headaches haha. I would advise creating a super set of the mesh class to automate it :+1: 

In any case its more of a temporay fix than anything, maybe you will find a better solution and if you do I am very intersted ;)

**Comment by NB2002** [comment]
Thanks for the quick reply! I will try the solution later today.

You are suggesting that it's a bug of BabylonJS. I think we should post this on the official Babylon forum or ping a developer from the Babylon team here. Maybe they can provide a permanent solution / fix the bug in Babylon.
