### ISSUE TITLE
A question about using this with WebGL2 and TWGL

### ISSUE THREAD

**Issue by ianskoo** [BarthPaleologue/volumetric-atmospheric-scattering#7]
Hello, first of all thank you very much for your work. I was looking for a not too complicated atmosphere for my thesis project, and although I watched Sebastian Lague's video, I did not really have time to port his C# implementation to JS and WebGL2. Thank you for doing this. 

Now, I am having some issues adapting your work into my project, and I was wondering whether you might have some quick ideas of what could be wrong by looking at the parameters I use and some screenshots. I should say that my project doesn't use an engine like Babylon, only WebGL2 and TWGL, which is a small helper that shortens some WebGL2 boilerplate code. I therefore create a depth texture after rendering the model onto a framebuffer and give that to your shader. 

The relevant parameters I'm using are:
atmosphereRadius: 84.78635437881874
planetRadius: 83.47610319076715
falloffFactor     : 1
sunIntensity      : 15
scatteringStrength: 1
densityModifier   : 1
redWaveLength     : 700
greenWaveLength   : 530
blueWaveLength    : 440
planetPosition:
- 0: 9.588249999999999
- 1: 46.7641
- 2: -83.47610319076715
cameraFar: 100
cameraNear: 0.0001
textureSampler: colorTexture,
depthSampler: depthTexture,

The planet position is calculated with real life Earth sizes mapped to the coordinate system of the world model. I have a small region of the earth as model at approx coordinates (9.5, 46.7, 0) so I thought to form the atmosphere underneath it by placing the planetPosition at those coordinates - planetRadius (at scale of the world model coordinates). These are some pictures of the result:

![Screenshot 2024-07-23 at 16 30 09](https://github.com/user-attachments/assets/88ed6cb5-6d52-4fbd-a8c5-da4837316fd6)
![Screenshot 2024-07-23 at 16 30 43](https://github.com/user-attachments/assets/59d1a4f1-e30b-4a28-98f4-ebcd9f5a2a68)
![Screenshot 2024-07-23 at 16 30 50](https://github.com/user-attachments/assets/cfbeadec-4db4-43de-ba54-e00342147af5)
![Screenshot 2024-07-23 at 16 30 56](https://github.com/user-attachments/assets/ad960843-0177-4819-bdd5-28892bda5aa3)
![Screenshot 2024-07-23 at 16 31 06](https://github.com/user-attachments/assets/35617736-3353-4716-babc-1da06182e42f)

Thank you in advance for your time and any help you can give me :)

**Comment by BarthPaleologue** [comment]
Hey there! Thanks for using this project ;) 

I think you are having an issue with the depth texture. My shader assumes it has been linearized, but without an engine you are probably using the non-linear depth.

In that cas you would have to do some changes to get the proper world position of each of your pixels by creating the clip space position with the uv and depth information and use the inverse projection and view matrices to find the world position.

The other solution is of course to linearize the depth texture, but that seems more work (Babylon is doing it for me here)

**Comment by ianskoo** [comment]
Thank you for the blazingly fast reply. This one liner by chatgpt to linearize each depth sample indeed made the atmosphere look much better with the same parameters: `(2.0 * cameraNear * cameraFar) / (cameraFar + cameraNear - z_depth * (cameraFar - cameraNear))`

![Screenshot 2024-07-23 at 17 10 19](https://github.com/user-attachments/assets/cb33da9b-45c2-4107-bf21-8720af9adda6)

I suppose I just have to find the right parameterization now to make it look as close to reality as possible. Thank you very much!

**Comment by BarthPaleologue** [comment]
I checked as well, and your formula is correct given that you remapped the texture depth (between 0 and 1) to WebGL NDC depth (between -1 and 1)

**Comment by ianskoo** [comment]
Thank you so much!
